// Mock product data with enhanced vehicle compatibility and category information
export const products = [
  {
    id: "1",
    name: "Toyota Corolla LED Headlight Assembly",
    price: 12500,
    originalPrice: 15000,
    discount: 17,
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    sku: "TYT-HL-LED-001",
    brand: "TYT Genuine Parts",
    category: "Headlights",
    mainCategory: "Lighting",
    subCategory: "Headlight Assemblies",
    compatibility: [
      { year: "2018", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2019", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2020", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2021", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2022", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2020", make: "Toyota", model: "Corolla Cross", engine: "1.8 G CVT" },
      { year: "2021", make: "Toyota", model: "Corolla Cross", engine: "1.8 G CVT" },
      { year: "2022", make: "Toyota", model: "Corolla Cross", engine: "1.8 G CVT" },
    ],
    compatibilityText: ["Toyota Corolla 2018-2022", "Toyota Corolla Cross 2020-2022"],
    description:
      "Genuine Toyota LED Headlight Assembly for Corolla models. This direct replacement headlight features advanced LED technology for superior brightness and visibility. The assembly includes the complete housing, LED bulbs, and wiring harness for a direct plug-and-play installation.",
    features: [
      "Direct OEM replacement",
      "Plug-and-play installation",
      "Advanced LED technology",
      "Weather-sealed housing",
      "DOT/SAE compliant",
      "Includes mounting hardware",
    ],
    specifications: {
      "Part Number": "TYT-81150-02G40",
      "Light Source": "LED",
      Position: "Driver Side (Left)",
      "Housing Color": "Black",
      "Lens Material": "Polycarbonate",
      Voltage: "12V",
      Certification: "DOT/SAE Compliant",
    },
    images: ["/honda-headlight.png", "/projector-headlight.png", "/hyundai-led-headlight.png"],
    installationGuide:
      "Remove the old headlight assembly by unscrewing the mounting bolts. Disconnect the wiring harness. Install the new assembly in reverse order. No special tools required.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "2",
    name: "Bilstein B6 Shock Absorber",
    price: 8500,
    originalPrice: 9500,
    discount: 11,
    rating: 4.9,
    reviewCount: 87,
    stock: 8,
    sku: "BIL-B6-24-031153",
    brand: "Bilstein",
    category: "Suspension",
    mainCategory: "Brakes & Suspension",
    subCategory: "Shock Absorbers",
    compatibility: [
      { year: "2016", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2017", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2018", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2019", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2020", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2021", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2022", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2016", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2017", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2018", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2019", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2020", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2021", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2022", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
    ],
    compatibilityText: ["Toyota Fortuner 2016-2022", "Mitsubishi Montero Sport 2016-2022"],
    description:
      "Bilstein B6 Heavy Duty shock absorbers provide improved handling and control for your vehicle. These high-performance monotube gas pressure shock absorbers are designed as direct replacements for your factory units, offering superior damping and control.",
    features: [
      "Monotube gas pressure technology",
      "Direct fit replacement",
      "Improved handling and control",
      "Reduced body roll",
      "Increased stability",
      "Fade-free performance",
    ],
    specifications: {
      "Part Number": "BIL-24-031153",
      Type: "Monotube Gas Pressure",
      Position: "Front",
      "Extended Length": "560mm",
      "Compressed Length": "345mm",
      "Top Mount": "OEM Style",
      "Bottom Mount": "Loop Eye",
    },
    images: ["/shock-absorber.png", "/bilstein-logo.png"],
    installationGuide:
      "Professional installation recommended. Remove wheel, remove old shock absorber, install new shock absorber, torque to manufacturer specifications.",
    warranty: "2 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "14-day return policy for unused items in original packaging",
  },
  {
    id: "3",
    name: "K&N High-Flow Air Filter",
    price: 2500,
    originalPrice: 2800,
    discount: 11,
    rating: 4.7,
    reviewCount: 203,
    stock: 25,
    sku: "KN-33-2031",
    brand: "K&N",
    category: "Engine",
    mainCategory: "Engine & Drivetrain",
    subCategory: "Air Filters",
    compatibility: [
      { year: "2016", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2017", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2018", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2019", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2020", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2021", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2022", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2017", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2018", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2019", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2020", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2021", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2022", make: "Honda", model: "CR-V", engine: "1.6 S Diesel 9AT" },
      { year: "2018", make: "Honda", model: "Accord", engine: "1.5 S Turbo CVT" },
      { year: "2019", make: "Honda", model: "Accord", engine: "1.5 S Turbo CVT" },
      { year: "2020", make: "Honda", model: "Accord", engine: "1.5 S Turbo CVT" },
      { year: "2021", make: "Honda", model: "Accord", engine: "1.5 S Turbo CVT" },
      { year: "2022", make: "Honda", model: "Accord", engine: "1.5 S Turbo CVT" },
    ],
    compatibilityText: ["Honda Civic 2016-2022", "Honda CR-V 2017-2022", "Honda Accord 2018-2022"],
    description:
      "K&N High-Flow Air Filters are designed to increase horsepower and acceleration while providing excellent filtration. This washable and reusable air filter is a direct replacement for your stock air filter, providing better airflow for improved engine performance.",
    features: [
      "Washable and reusable",
      "Million Mile Limited Warranty",
      "Increases horsepower",
      "Improves acceleration",
      "Excellent filtration",
      "Eco-friendly (reusable)",
    ],
    specifications: {
      "Part Number": "KN-33-2031",
      Height: "3.2 cm",
      "Outside Length": "25.7 cm",
      "Outside Width": "16.5 cm",
      "Filtration Material": "Cotton Gauze",
      Shape: "Panel",
      Warranty: "Million Mile Limited Warranty",
    },
    images: ["/air-filter.png", "/k&n-logo.png"],
    installationGuide: "Open air box, remove old filter, insert K&N filter, close air box. No special tools required.",
    warranty: "Million Mile Limited Warranty",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "4",
    name: "Brembo Sport Brake Disc",
    price: 6800,
    originalPrice: 7500,
    discount: 9,
    rating: 4.9,
    reviewCount: 156,
    stock: 12,
    sku: "BRE-09.C602.11",
    brand: "Brembo",
    category: "Brakes",
    mainCategory: "Brakes & Suspension",
    subCategory: "Brake Discs",
    compatibility: [
      { year: "2016", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2017", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2018", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2019", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2020", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2021", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2022", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2015", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2016", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2017", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2018", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2019", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2020", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2021", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
      { year: "2022", make: "Toyota", model: "Hilux", engine: "2.4 G DSL 4x2 MT" },
    ],
    compatibilityText: ["Toyota Fortuner 2016-2022", "Toyota Hilux 2015-2022"],
    description:
      "Brembo Sport Brake Discs are designed to provide superior braking performance for your vehicle. These high-performance discs feature cross-drilling and slotting for improved heat dissipation and pad cleaning, resulting in consistent braking performance even under demanding conditions.",
    features: [
      "Cross-drilled and slotted design",
      "Improved heat dissipation",
      "Better wet braking performance",
      "Reduced brake fade",
      "Direct OEM replacement",
      "High-carbon cast iron construction",
    ],
    specifications: {
      "Part Number": "BRE-09.C602.11",
      Diameter: "330mm",
      Thickness: "28mm",
      "Minimum Thickness": "26mm",
      "Center Hole Diameter": "67mm",
      PCD: "5x114.3mm",
      "Surface Treatment": "Cross-drilled and slotted",
    },
    images: ["/brake-disc.png", "/brembo-logo.png"],
    installationGuide:
      "Professional installation recommended. Remove wheel, remove caliper, remove old disc, install new disc, reinstall caliper, torque to manufacturer specifications.",
    warranty: "2 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "14-day return policy for unused items in original packaging",
  },
  {
    id: "5",
    name: "NGK Laser Iridium Spark Plugs (Set of 4)",
    price: 3200,
    originalPrice: 3600,
    discount: 11,
    rating: 4.8,
    reviewCount: 189,
    stock: 30,
    sku: "NGK-SILZKR7C11S-4",
    brand: "NGK",
    category: "Engine",
    mainCategory: "Engine & Drivetrain",
    subCategory: "Spark Plugs",
    compatibility: [
      { year: "2016", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2017", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2018", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2019", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2020", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2021", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2022", make: "Toyota", model: "Vios", engine: "1.5 G MT" },
      { year: "2017", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
      { year: "2018", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
      { year: "2019", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
      { year: "2020", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
      { year: "2021", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
      { year: "2022", make: "Toyota", model: "Altis", engine: "1.6 G MT" },
    ],
    compatibilityText: ["Toyota Vios 2016-2022", "Toyota Altis 2017-2022"],
    description:
      "NGK Laser Iridium Spark Plugs feature a 0.6mm laser-welded fine iridium tip that provides superior ignitability and longer service life. These spark plugs are designed to improve fuel efficiency, lower emissions, and provide better throttle response.",
    features: [
      "0.6mm laser-welded fine iridium tip",
      "Longer service life (up to 100,000 km)",
      "Improved fuel efficiency",
      "Better throttle response",
      "Lower emissions",
      "Stable idle",
    ],
    specifications: {
      "Part Number": "SILZKR7C11S",
      "Thread Size": "14mm",
      Reach: "19mm",
      "Hex Size": "16mm",
      Gap: "1.1mm",
      "Seat Type": "Gasket",
      Quantity: "Set of 4",
    },
    images: ["/spark-plugs.png"],
    installationGuide:
      "Remove engine cover if necessary. Remove ignition coils. Remove old spark plugs using a spark plug socket. Check and adjust gap if necessary. Install new spark plugs and torque to 25-30 Nm. Reinstall ignition coils and engine cover.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "6",
    name: "Toyota Genuine Oil Filter",
    price: 450,
    originalPrice: 500,
    discount: 10,
    rating: 4.6,
    reviewCount: 215,
    stock: 50,
    sku: "TYT-90915-YZZF1",
    brand: "Toyota",
    category: "Engine",
    mainCategory: "Engine & Drivetrain",
    subCategory: "Oil Filters",
    compatibility: [
      { year: "2014", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2015", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2016", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2017", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2018", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2019", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2020", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2021", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2022", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2014", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2015", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2016", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2017", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2018", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2019", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2020", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2021", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2022", make: "Toyota", model: "Corolla", engine: "1.6 G MT" },
      { year: "2016", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2017", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2018", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2019", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2020", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2021", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2022", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
    ],
    compatibilityText: ["Toyota Vios 2014-2022", "Toyota Corolla 2014-2022", "Toyota Fortuner 2016-2022"],
    description:
      "Toyota Genuine Oil Filter is designed specifically for Toyota vehicles to ensure optimal engine performance and longevity. This filter effectively removes contaminants from engine oil, preventing engine wear and extending oil life.",
    features: [
      "Genuine Toyota part",
      "Superior filtration efficiency",
      "Anti-drainback valve prevents dry starts",
      "Heavy-duty steel case for durability",
      "Silicone anti-drainback valve",
      "High-capacity filtering media",
    ],
    specifications: {
      "Part Number": "90915-YZZF1",
      "Filter Type": "Spin-on",
      "Thread Size": "M20x1.5",
      Diameter: "68mm",
      Height: "65mm",
      "Bypass Valve": "Yes",
      "Anti-Drainback Valve": "Yes",
    },
    images: ["/oil-filter.png"],
    installationGuide:
      "Drain engine oil. Remove old filter using an oil filter wrench. Apply thin film of oil to new filter gasket. Install new filter hand-tight plus 3/4 turn. Refill with recommended engine oil. Check for leaks.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "7",
    name: "Bosch Wiper Blades (Pair)",
    price: 1200,
    originalPrice: 1400,
    discount: 14,
    rating: 4.5,
    reviewCount: 178,
    stock: 35,
    sku: "BOSCH-3397007297",
    brand: "Bosch",
    category: "Exterior",
    mainCategory: "Exterior Parts",
    subCategory: "Wiper Blades",
    compatibility: [
      // Universal fit for most vehicles
      { year: "2018", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2019", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2020", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2021", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2022", make: "Toyota", model: "Vios", engine: "1.3 E MT" },
      { year: "2018", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2019", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2020", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2021", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2022", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2018", make: "Mitsubishi", model: "Mirage", engine: "GLX MT" },
      { year: "2019", make: "Mitsubishi", model: "Mirage", engine: "GLX MT" },
      { year: "2020", make: "Mitsubishi", model: "Mirage", engine: "GLX MT" },
      { year: "2021", make: "Mitsubishi", model: "Mirage", engine: "GLX MT" },
      { year: "2022", make: "Mitsubishi", model: "Mirage", engine: "GLX MT" },
      { year: "2018", make: "Nissan", model: "Almera", engine: "1.5 E MT" },
      { year: "2019", make: "Nissan", model: "Almera", engine: "1.5 E MT" },
      { year: "2020", make: "Nissan", model: "Almera", engine: "1.5 E MT" },
      { year: "2021", make: "Nissan", model: "Almera", engine: "1.5 E MT" },
      { year: "2022", make: "Nissan", model: "Almera", engine: "1.5 E MT" },
      { year: "2018", make: "Hyundai", model: "Accent", engine: "1.4 GL MT" },
      { year: "2019", make: "Hyundai", model: "Accent", engine: "1.4 GL MT" },
      { year: "2020", make: "Hyundai", model: "Accent", engine: "1.4 GL MT" },
      { year: "2021", make: "Hyundai", model: "Accent", engine: "1.4 GL MT" },
      { year: "2022", make: "Hyundai", model: "Accent", engine: "1.4 GL MT" },
    ],
    compatibilityText: ["Universal fit for most vehicles"],
    description:
      "Bosch Wiper Blades provide superior visibility in all weather conditions. These premium wiper blades feature a patented beam design with a precision-cut natural rubber wiping edge for a clean, streak-free wipe and longer performance life.",
    features: [
      "Patented beam design",
      "Precision-cut natural rubber wiping edge",
      "Aerodynamic wind spoiler",
      "Weather-resistant construction",
      "Easy installation",
      "Quiet operation",
    ],
    specifications: {
      "Part Number": "3397007297",
      Type: "Beam",
      Length: '24"/18" (Driver/Passenger)',
      Material: "Natural Rubber with Graphite Coating",
      "Connector Type": "Universal Hook",
      "Weather Resistance": "All-Weather",
      "Noise Level": "Low",
    },
    images: ["/wiper-blades.png"],
    installationGuide:
      "Lift wiper arm away from windshield. Press release tab on existing blade and slide off. Align new wiper blade with wiper arm and slide on until it clicks into place. Lower wiper arm back to windshield.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "8",
    name: "Honda Civic Front Bumper",
    price: 15000,
    originalPrice: 18000,
    discount: 17,
    rating: 4.7,
    reviewCount: 65,
    stock: 5,
    sku: "HON-71101-TBA-A00",
    brand: "Honda",
    category: "Body",
    mainCategory: "Body Parts & Mirrors",
    subCategory: "Bumper Covers",
    compatibility: [
      { year: "2016", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2017", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2018", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2019", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
      { year: "2020", make: "Honda", model: "Civic", engine: "1.5 S Turbo CVT" },
    ],
    compatibilityText: ["Honda Civic 2016-2020"],
    description:
      "Genuine Honda Civic Front Bumper designed as a direct replacement for your vehicle. This bumper is manufactured to the same specifications as the original part, ensuring perfect fit and finish for your Honda Civic.",
    features: [
      "Genuine Honda part",
      "Direct replacement",
      "Perfect fit and finish",
      "Made from high-quality materials",
      "Durable construction",
      "Factory paint-ready surface",
    ],
    specifications: {
      "Part Number": "71101-TBA-A00",
      Material: "High-impact plastic",
      Position: "Front",
      Color: "Primed (ready for paint)",
      "Includes Grille": "No",
      "Includes Fog Light Holes": "Yes",
      "Includes Hardware": "Basic mounting hardware included",
    },
    images: ["/car-bumper.png"],
    installationGuide:
      "Professional installation recommended. Remove old bumper by disconnecting fog lights, sensors, and mounting hardware. Install new bumper by reversing removal process. Painting required before installation.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱350 for Express Shipping (2-3 business days).",
    returnPolicy: "14-day return policy for unused items in original packaging",
  },
  {
    id: "9",
    name: "Mitsubishi Montero Sport Tail Light Assembly",
    price: 8900,
    originalPrice: 10500,
    discount: 15,
    rating: 4.8,
    reviewCount: 92,
    stock: 7,
    sku: "MIT-8330A787",
    brand: "Mitsubishi",
    category: "Lighting",
    mainCategory: "Headlights & Lighting",
    subCategory: "Tail Lights",
    compatibility: [
      { year: "2016", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2017", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2018", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2019", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2020", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2021", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
      { year: "2022", make: "Mitsubishi", model: "Montero Sport", engine: "2.4 GLS 4x2 AT" },
    ],
    compatibilityText: ["Mitsubishi Montero Sport 2016-2022"],
    description:
      "Genuine Mitsubishi Tail Light Assembly for Montero Sport. This direct replacement tail light features LED technology for superior brightness and visibility. The assembly includes the complete housing, LED bulbs, and wiring harness for a direct plug-and-play installation.",
    features: [
      "Genuine Mitsubishi part",
      "LED technology",
      "Direct replacement",
      "Plug-and-play installation",
      "Weather-sealed housing",
      "DOT/SAE compliant",
    ],
    specifications: {
      "Part Number": "8330A787",
      "Light Source": "LED",
      Position: "Driver Side (Left)",
      "Housing Color": "Red/Clear",
      "Lens Material": "Polycarbonate",
      Voltage: "12V",
      Certification: "DOT/SAE Compliant",
    },
    images: ["/car-tail-lights.png"],
    installationGuide:
      "Open trunk/hatch. Remove access panel. Disconnect electrical connector. Remove mounting nuts/bolts. Remove old tail light assembly. Install new assembly in reverse order. No special tools required.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
  {
    id: "10",
    name: "Toyota Fortuner Side Mirror",
    price: 5500,
    originalPrice: 6200,
    discount: 11,
    rating: 4.6,
    reviewCount: 78,
    stock: 10,
    sku: "TYT-87910-0K870",
    brand: "Toyota",
    category: "Exterior",
    mainCategory: "Body Parts & Mirrors",
    subCategory: "Mirrors",
    compatibility: [
      { year: "2016", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2017", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2018", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2019", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2020", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2021", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
      { year: "2022", make: "Toyota", model: "Fortuner", engine: "2.4 G Diesel 4x2 MT" },
    ],
    compatibilityText: ["Toyota Fortuner 2016-2022"],
    description:
      "Genuine Toyota Side Mirror for Fortuner models. This direct replacement mirror features power adjustment, heated glass, and integrated turn signal. The assembly includes the complete housing, mirror glass, and wiring harness for a direct plug-and-play installation.",
    features: [
      "Genuine Toyota part",
      "Power adjustment",
      "Heated mirror glass",
      "Integrated turn signal",
      "Foldable design",
      "Weather-resistant construction",
    ],
    specifications: {
      "Part Number": "87910-0K870",
      Position: "Driver Side (Left)",
      "Housing Color": "Black (paintable)",
      "Mirror Type": "Convex",
      Adjustment: "Power",
      Heated: "Yes",
      "Turn Signal": "Yes",
    },
    images: ["/car-mirrors.png"],
    installationGuide:
      "Remove door panel. Disconnect electrical connectors. Remove mounting bolts. Remove old mirror. Install new mirror in reverse order. Painting may be required to match vehicle color.",
    warranty: "1 year manufacturer warranty against defects",
    shipping: "Available in Metro Manila and Select Urban Areas only. ₱250 for Standard Shipping (3-5 business days).",
    returnPolicy: "30-day return policy for unused items in original packaging",
  },
]

export function getProductById(id: string) {
  return products.find((product) => product.id === id)
}

export function getRelatedProducts(currentProductId: string, category: string, limit = 4) {
  return products.filter((product) => product.id !== currentProductId && product.category === category).slice(0, limit)
}

export function getProductsByCategory(category: string) {
  return products.filter((product) => product.category === category)
}

export function getAllProducts() {
  return products
}

// New function to get products by vehicle
export function getProductsByVehicle(year: string, make: string, model: string, engine: string) {
  return products.filter((product) =>
    product.compatibility.some(
      (compat) => compat.year === year && compat.make === make && compat.model === model && compat.engine === engine,
    ),
  )
}

// New function to get products by main category
export function getProductsByMainCategory(mainCategory: string) {
  return products.filter((product) => product.mainCategory === mainCategory)
}

// New function to get products by sub category
export function getProductsBySubCategory(subCategory: string) {
  return products.filter((product) => product.subCategory === subCategory)
}
