// Mock product data for the product listing page
export const products = [
  {
    id: "toyota-headlight-assembly",
    name: "Toyota Vios 2019-2022 Headlight Assembly",
    price: 4850,
    originalPrice: 5500,
    discount: 12,
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    sku: "TYT-HL-VS19-R",
    brand: "Toyota",
    category: "Headlights",
    image: "/honda-headlight.png",
  },
  {
    id: "honda-city-headlight",
    name: "Honda City 2020-2023 LED Headlight",
    price: 5200,
    originalPrice: 5800,
    discount: 10,
    rating: 4.7,
    reviewCount: 98,
    stock: 8,
    sku: "HND-HL-CT20-L",
    brand: "Honda",
    category: "Headlights",
    image: "/projector-headlight.png",
  },
  {
    id: "mitsubishi-mirage-headlight",
    name: "Mitsubishi Mirage G4 Headlight Assembly",
    price: 4200,
    rating: 4.5,
    reviewCount: 76,
    stock: 12,
    sku: "MTS-HL-MG4-R",
    brand: "Mitsubishi",
    category: "Headlights",
    image: "/hyundai-led-headlight.png",
  },
  {
    id: "brake-pad-set",
    name: "Premium Ceramic Brake Pad Set",
    price: 2450,
    originalPrice: 2800,
    discount: 13,
    rating: 4.7,
    reviewCount: 89,
    stock: 23,
    sku: "BRK-PD-CRM-01",
    brand: "Brembo",
    category: "Brakes",
    image: "/brake-pads-close-up.png",
  },
  {
    id: "brake-disc-rotor",
    name: "Performance Brake Disc Rotor",
    price: 3200,
    rating: 4.6,
    reviewCount: 65,
    stock: 18,
    sku: "BRK-DSC-PRF-01",
    brand: "Brembo",
    category: "Brakes",
    image: "/brake-disc.png",
  },
  {
    id: "brake-hose-kit",
    name: "Stainless Steel Brake Hose Kit",
    price: 1850,
    originalPrice: 2100,
    discount: 12,
    rating: 4.4,
    reviewCount: 42,
    stock: 7,
    sku: "BRK-HS-SS-01",
    brand: "K&N",
    category: "Brakes",
    image: "/brake-hose.png",
  },
  {
    id: "toyota-bumper",
    name: "Toyota Fortuner Front Bumper",
    price: 8500,
    rating: 4.5,
    reviewCount: 34,
    stock: 5,
    sku: "TYT-BMP-FRT-01",
    brand: "Toyota",
    category: "Body",
    image: "/car-bumper.png",
  },
  {
    id: "honda-fender",
    name: "Honda Civic Front Fender",
    price: 3800,
    originalPrice: 4200,
    discount: 10,
    rating: 4.6,
    reviewCount: 28,
    stock: 9,
    sku: "HND-FND-CVC-01",
    brand: "Honda",
    category: "Body",
    image: "/car-fenders.png",
  },
  {
    id: "nissan-grille",
    name: "Nissan Navara Front Grille",
    price: 4500,
    rating: 4.3,
    reviewCount: 19,
    stock: 6,
    sku: "NSN-GRL-NVR-01",
    brand: "Nissan",
    category: "Body",
    image: "/car-grille.png",
  },
  {
    id: "mitsubishi-door",
    name: "Mitsubishi Montero Door Shell",
    price: 12500,
    rating: 4.7,
    reviewCount: 15,
    stock: 3,
    sku: "MTS-DR-MNT-01",
    brand: "Mitsubishi",
    category: "Body",
    image: "/car-door-shell.png",
  },
  {
    id: "hyundai-trunk",
    name: "Hyundai Accent Trunk Lid",
    price: 7800,
    originalPrice: 8500,
    discount: 8,
    rating: 4.4,
    reviewCount: 12,
    stock: 4,
    sku: "HYN-TRK-ACC-01",
    brand: "Hyundai",
    category: "Body",
    image: "/car-trunk-lid.png",
  },
  {
    id: "toyota-radiator",
    name: "Toyota Innova Radiator Support",
    price: 5200,
    rating: 4.5,
    reviewCount: 23,
    stock: 7,
    sku: "TYT-RAD-INV-01",
    brand: "Toyota",
    category: "Body",
    image: "/car-radiator-support.png",
  },
  {
    id: "oil-filter-toyota",
    name: "Toyota Oil Filter",
    price: 350,
    originalPrice: 400,
    discount: 13,
    rating: 4.8,
    reviewCount: 156,
    stock: 45,
    sku: "TYT-OIL-FLT-01",
    brand: "Toyota",
    category: "Engine",
    image: "/oil-filter.png",
  },
  {
    id: "air-filter-kn",
    name: "K&N Performance Air Filter",
    price: 1850,
    originalPrice: 2100,
    discount: 12,
    rating: 4.9,
    reviewCount: 87,
    stock: 23,
    sku: "KN-AIR-FLT-01",
    brand: "K&N",
    category: "Engine",
    image: "/air-filter.png",
  },
  {
    id: "spark-plugs-set",
    name: "Iridium Spark Plugs Set of 4",
    price: 1200,
    rating: 4.7,
    reviewCount: 64,
    stock: 18,
    sku: "SPK-PLG-IR-04",
    brand: "K&N",
    category: "Engine",
    image: "/spark-plugs.png",
  },
  {
    id: "wiper-blades-bosch",
    name: "Bosch Wiper Blades Set",
    price: 950,
    originalPrice: 1100,
    discount: 14,
    rating: 4.6,
    reviewCount: 92,
    stock: 0, // Out of stock
    sku: "WPR-BLD-BSH-01",
    brand: "Bilstein",
    category: "Exterior",
    image: "/wiper-blades.png",
  },
  {
    id: "koni-shock-absorbers",
    name: "Koni Sport Shock Absorbers",
    price: 12500,
    originalPrice: 13800,
    discount: 9,
    rating: 4.9,
    reviewCount: 47,
    stock: 6,
    sku: "KNI-SHK-SPT-01",
    brand: "Koni",
    category: "Suspension",
    image: "/shock-absorber.png",
  },
  {
    id: "catalytic-converter",
    name: "Universal Catalytic Converter",
    price: 8500,
    rating: 4.3,
    reviewCount: 28,
    stock: 5,
    sku: "CAT-CNV-UNV-01",
    brand: "K&N",
    category: "Engine",
    image: "/car-catalytic-converter.png",
  },
  {
    id: "engine-mount-toyota",
    name: "Toyota Vios Engine Mount",
    price: 2800,
    rating: 4.5,
    reviewCount: 36,
    stock: 12,
    sku: "TYT-ENG-MNT-01",
    brand: "Toyota",
    category: "Engine",
    image: "/car-engine-parts.png",
  },
  {
    id: "seat-covers-premium",
    name: "Premium Leather Seat Covers",
    price: 4500,
    originalPrice: 5200,
    discount: 13,
    rating: 4.7,
    reviewCount: 53,
    stock: 8,
    sku: "INT-ST-CVR-01",
    brand: "Bilstein",
    category: "Interior",
    image: "/car-interior-accessories.png",
  },
  {
    id: "tool-set-comprehensive",
    name: "Comprehensive Automotive Tool Set",
    price: 7500,
    originalPrice: 8200,
    discount: 9,
    rating: 4.8,
    reviewCount: 42,
    stock: 6,
    sku: "TLS-SET-CMP-01",
    brand: "Bilstein",
    category: "Tools",
    image: "/automotive-tools.png",
  },
]
